import "../styles/global.css";
import Navigation from "@/components/Navigation/Navigation";
import Footer from "@/components/footer/Footer";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
