import "../styles/global.css";
import Footer from "@/components/footer/Footer";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        {children}
        <Footer />
        <h1>RootLayout</h1>
      </body>
    </html>
  );
}
